`Scala` 的 `catch` 子句中，使用的是匹配的方法，内为一系列 `case` 子句

```scala
try {
    // sth
} catch {
    case ex: Exception => //...
} finally {
    //...
}
```

所有的异常继承自 `Throwable`。如果没有匹配到则会 `throw` 出该异常。

‍
